### ISSUE TITLE
Key Error 'Apps key'

### ISSUE THREAD

**Issue by DandyFabian** [sheeriot/bulk-e#13]
I had problem when I try to bulk register OTAA device, it give be apps key problem which only happened when you use ABP device.

The following is the error and the CSV file that i used

"
Devices Filename: imports/runX-devices.csv
Commons Filename: imports/runX-common.csv
Logging Filename: imports/runX-logging.txt
Traceback (most recent call last):
  File "C:\Users\Dandy\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'appskey'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python385\bulk-e.py", line 70, in <module>
    deviceimport_df = deviceimport_df.assign(appskey = str(commons_df['appskey'][0]))
  File "C:\Users\Dandy\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 3807, in getitem
    indexer = self.columns.get_loc(key)
  File "C:\Users\Dandy\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'appskey' "

[runX-common.csv](https://github.com/sheeriot/bulk-e/files/11790342/runX-common.csv)
[runX-devices.csv](https://github.com/sheeriot/bulk-e/files/11790343/runX-devices.csv)

**Comment by krisdthompson** [comment]
This has been fixed.
